import { StudioPreset } from './types';

export const STUDIO_PRESETS: StudioPreset[] = [
  {
    id: 'cyberpunk-dither',
    name: '80s Cyberpunk Neon',
    description: 'Fine Bayer 8x8 dither with RGB channel split & cyan/magenta vibes',
    badge: 'Popular',
    dither: {
      algo: 13, // Bayer 8x8
      mode: 0,
      levels: 3,
      scale: 1,
      threshold: 50,
      spread: 110,
      contrast: 120,
    },
    grain: { enabled: false },
    vhs: { enabled: false },
    ntsc: { enabled: false },
    channels: { enabled: true, amount: 6, angle: 0, radial: false, jitter: 1.5 },
    lines: { enabled: false },
  },
  {
    id: 'kodak-16mm',
    name: 'Kodak Vision3 16mm Film',
    description: 'Authentic 16mm film stock with organic silver-halide crystal response',
    badge: 'Cinematic',
    dither: { algo: 16, mode: 0, spread: 0 }, // pass-through
    grain: {
      enabled: true,
      sizeMm: 16,
      amount: 65,
      density: 90,
      contrast: 100,
      softness: 35,
      shadows: 90,
      midtones: 100,
      highlights: 45,
      colorMode: true,
      autoAnim: true,
      speed: 100,
    },
    vhs: { enabled: false },
    ntsc: { enabled: false },
    channels: { enabled: false },
    lines: { enabled: false },
  },
  {
    id: 'vhs-rental-tape',
    name: '1987 VHS Rental Tape',
    description: 'Tracking wobble, head-switch skew, tape static, and scanline dropouts',
    badge: 'Retro',
    dither: { algo: 16, mode: 0, spread: 0 },
    grain: { enabled: false },
    vhs: {
      enabled: true,
      trackAmount: 25,
      headSwitch: 35,
      jitter: 15,
      vertInstability: 10,
      staticAmount: 40,
      scanlines: 40,
      scanPitch: 3,
      speed: 100,
    },
    ntsc: { enabled: false },
    channels: { enabled: true, amount: 2, angle: 90, radial: false, jitter: 0 },
    lines: { enabled: false },
  },
  {
    id: 'ntsc-crt-broadcast',
    name: 'NTSC 3.58MHz CRT Monitor',
    description: 'Composite subcarrier dot crawl, rainbow cross-color, and RF snow',
    badge: 'Broadcast',
    dither: { algo: 16, mode: 0, spread: 0 },
    grain: { enabled: false },
    vhs: { enabled: false },
    ntsc: {
      enabled: true,
      dotCrawl: 60,
      chromaBleed: 50,
      carrierFreq: 100,
      phaseSkew: 25,
      ghosting: 30,
      ringing: 35,
      scanlines: 45,
      rfSnow: 20,
    },
    channels: { enabled: false },
    lines: { enabled: false },
  },
  {
    id: 'halftone-print',
    name: 'Vintage Newspaper Halftone',
    description: '45° continuous Euclidean halftone dot screen with high-contrast inks',
    badge: 'Print',
    dither: {
      algo: 18, // Halftone Dot 45°
      mode: 1,  // Monochrome
      levels: 2,
      scale: 1,
      threshold: 52,
      spread: 120,
      patternScale: 110,
      contrast: 130,
    },
    grain: { enabled: false },
    vhs: { enabled: false },
    ntsc: { enabled: false },
    channels: { enabled: false },
    lines: { enabled: false },
  },
  {
    id: 'hair-contour-scribble',
    name: 'Edge-Guided Strand Tracer',
    description: 'Object edge detection tracing organic hair and scribble contours',
    badge: 'Generative',
    dither: { algo: 16, mode: 0, spread: 0 },
    grain: { enabled: false },
    vhs: { enabled: false },
    ntsc: { enabled: false },
    channels: { enabled: false },
    lines: {
      enabled: true,
      amount: 800,
      length: 45,
      width: 1.2,
      curvature: 20,
      kink: 30,
      opacity: 85,
      color: '#ffffff',
      autoAnim: true,
      speed: 100,
      objectMode: true,
      edgeThreshold: 25,
      edgeSensitivity: 75,
      edgeDirection: 0, // Along contour
    },
  },
];
